module.exports = [
    'Action',
    'Adventure',
    'Bishonen',
    'Bishoujo',
    'Comedy',
    'Cyberpunk',
    'Drama',
    'Fan Service',
    'Fantasy',
    'Harem',
    'Historical',
    'Horror',
    'Magical Girl',
    'Martial Arts',
    'Mecha',
    'Moe',
    'Mystery',
    'Reverse Harem',
    'Romance',
    'School',
    'Sci Fi',
    'Shonen',
    'Slice of Life',
    'Sports',
    'Super Power',
    'Supernatural',
    'Yuri',
];
